# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01260902bbcb7612a259dc5dd5ecddb0c677465174b5f251010547bfcb80243ae7b6f711bca4930ae982a2055b0ae7ca0767673db517257ba0d201489157815f

test:
  secret_key_base: 28dd112e9905fd2e4ea0ffcab98a63fab57222f1caf1652a3173eee18b196537d6bbd3e5605ff5700c5b934847100b08cf3921a384872bd4cbe2c42a22e16a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
